### ISSUE TITLE
patch doesn't apply when building DJGPP

### ISSUE THREAD

**Issue by SuperIlu** [jwt27/build-gcc#14]
Using this command line:
PREFIX=/home/ilu/djgpp473 ./build-djgpp.sh djgpp gcc-4.7.3 binutils-2.29.1

results in this error when unpacking(?) DJGPP (I pressed ENTER twice when the error was detected by patch):
make: Leaving directory '/home/ilu/build-gcc/build/djgpp-205/src/stub'
Installing djgpp headers
autoconf already built, skipping.
automake already built, skipping.
patching file unpack-gcc.sh
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file unpack-gcc.sh.rej

Host system is Ubuntu 18.04 LTS running on Win10 WSL1...

**Comment by jwt27** [comment]
Looks like the unpacking code in `unpack-gcc.sh` changed at one point. I'll have to figure out when that happened and add a second patch file for older versions.
