### ISSUE TITLE
Building DJGPP fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by manxorist** [jwt27/build-gcc#20]
https://github.com/jwt27/build-gcc/commit/98e62e0f1b145b2537326d9de4e3640071433f0e causes build to fail on Ubuntu 20.04 when targeting DJGPP:
```
checking whether to use python... /usr/bin/python2
checking for python2.7... no
configure: error: no usable python found at /usr/bin/python2
make[1]: *** [Makefile:9096: configure-gdb] Error 1
make[1]: Leaving directory '/home/manx/opt/djgpp-src/build-gcc/build/gdb-8.2.1/build-i386-pc-msdosdjgpp'
make: *** [Makefile:849: all] Error 2
```
I have both python2 and python3 installed.

This happens independently of whether `/usr/bin/python` is python2 or python3 (i.e. `python-is-python2` or `python-is-python3` packages installed).

**Comment by jwt27** [comment]
Hi, thanks for the report.
Seems gdb requires the Python C headers to be installed (package `python2-dev`).  I should document this in the readme too.

**Comment by manxorist** [comment]
Installing `python2-dev` solved the issue.

Thanks.
