### ISSUE TITLE
[DJGPP]xz: (stdin): Unexpected end of input after patching file unpack-gcc.sh

### ISSUE THREAD

**Issue by dufresnep** [jwt27/build-gcc#25]
Note: I had installed a cross-compiler on this Ubuntu in June 2021, for DJGPP, was working well, but not used it much
and forgot quite a bit about it.

Recloned in a new directory, then:
paul@kasparno:~/build-gcc2/build-gcc$ LANG=C bash build-djgpp.sh djgpp

(note that I did: rm -rf build, and retry once)
Got:
...
install-info: warning: no info dir entry in `/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/info/automake-history.info'
 /usr/bin/mkdir -p '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/man/man1'
 /usr/bin/install -c -m 644 doc/aclocal.1 doc/automake.1 doc/aclocal-1.15.1 doc/automake-1.15.1 '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/man/man1'
 /usr/bin/mkdir -p '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/Automake'
 /usr/bin/install -c -m 644 lib/Automake/Config.pm '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/Automake'
make  install-data-hook
make[2]: Entering directory '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/automake-1.15.1'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/config.guess'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/config.sub'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/install-sh'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/mdate-sh'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/missing'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/mkinstalldirs'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/ylwrap'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/depcomp'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/compile'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/py-compile'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/ar-lib'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/test-driver'
 chmod +x '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/share/automake-1.15/tap-driver.sh'
make[2]: Leaving directory '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/automake-1.15.1'
make[1]: Leaving directory '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/automake-1.15.1'
rm: cannot remove '/home/paul/build-gcc2/build-gcc/build/djcross-gcc-10.3.0/tmpinst/automake-*-built': No such file or directory
patching file unpack-gcc.sh
Hunk #2 succeeded at 61 (offset 7 lines).
Unpacking gcc...
xz: (stdin): Unexpected end of input
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
paul@kasparno:~/build-gcc2/build-gcc$

**Comment by jwt27** [comment]
Hi,
Your gcc archive seems to be corrupted or partially downloaded.  See if it matches this sha256sum:
`64f404c1a650f27fc33da242e1f2df54952e3963a49e06e73f6940f3223ac344  gcc-10.3.0.tar.xz`
I would suggest to remove it (from `download/`), then try again.  Maybe I should add checksums in the scripts themselves.

**Comment by dufresnep** [comment]
Yeah... it have only 4Mb:
paul@kasparno:~/build-gcc2/build-gcc/download$ sha256sum gcc-10.3.0.tar.xz 
98159f7b18722140965428e3b17871b4e77a6f941190eabef7d972c551bd1f29  gcc-10.3.0.tar.xz
paul@kasparno:~/build-gcc2/build-gcc/download$ ls -lh gcc-10.3.0.tar.xz 
-rw-r--r-- 1 paul paul 4,0M mar 20 21:26 gcc-10.3.0.tar.xz
paul@kasparno:~/build-gcc2/build-gcc/download$ 

will retry

**Comment by dufresnep** [comment]
Yes, it worked:
paul@kasparno:~/build-gcc2/build-gcc$ /usr/local/cross/bin/i386-pc-msdosdjgpp-gcc --version
i386-pc-msdosdjgpp-gcc (GCC) 10.3.0
