### ISSUE TITLE
please enable Kinetic build

### ISSUE THREAD

**Issue by stsp** [jwt27/build-gcc#26]
Thanks. :)

**Comment by jwt27** [comment]
Will do, thanks again for the reminder.

**Comment by stsp** [comment]
Thanks, getting a warning now:
```
W: http://ppa.launchpadcontent.net/jwt27/djgpp-toolchain/ubuntu/dists/kinetic/InRelease: Key is stored in legacy trusted.gpg
keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```
Not sure what does this mean.

**Comment by jwt27** [comment]
I also get a long list of those messages on my Debian-unstable system.  This happens now when you install a pgp key with `apt-key`, the whole `apt-key` program has been deprecated for some reason.  Instead you're supposed to download keys directly to `/etc/apt/trusted.gpg.d/*.asc` now.

**Comment by stsp** [comment]
But I am getting the warning here:
https://launchpadlibrarian.net/599625697/buildlog.txt.gz
Not a local build, but on an LP.

**Comment by jwt27** [comment]
Then the build scripts on LP haven't been updated yet and they still use `apt-key`.  I think it's a harmless message either way.
