### ISSUE TITLE
Please enable Noble build

### ISSUE THREAD

**Issue by stsp** [jwt27/build-gcc#38]
... on LP.
Thanks. :)

**Comment by jwt27** [comment]
Done!

Now I was wondering, how are you notified of new Ubuntu releases?  Is there some RSS feed or mailing list I can subscribe to?

**Comment by stsp** [comment]
Thanks. :)
https://lists.ubuntu.com/archives/ubuntu-devel/2023-October/042835.html
But actually I am not subscribed
to that list. I am just following the
local free-software news site, that
watches for such events and makes
the news from them.
I have to admit that not many alike
sites survived till our days, but this
one is very active.

**Comment by jwt27** [comment]
Oh I think I subscribed to the ubuntu-announce list at one point, but they only announce there when a release leaves beta, not when it's first opened for development.

Found this page on LP: https://launchpad.net/ubuntu/+series
Would be great if there was an RSS feed on there.  Maybe I can set up some cron script for page change notifications.
