### ISSUE TITLE
please enable aarch64 builds

### ISSUE THREAD

**Issue by stsp** [jwt27/build-gcc#39]
Thank you. :)

**Comment by jwt27** [comment]
Enabled it, not much seems to be happening.  Guess I need to push a new version?

I think I disabled aarch64 at one point to save space.  But I got the 8 GB upgrade now so we should be good.

**Comment by jwt27** [comment]
Oh, figured it out.  Should be building now!

**Comment by stsp** [comment]
The following packages have unmet dependencies:
 djgpp : Depends: zlib-djgpp-dev but it is not installable
         Depends: libssl-djgpp-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jwt27** [comment]
Yeah I need to update those too.  But you probably don't need the whole `djgpp` package.

**Comment by stsp** [comment]
If I don't need it, why not to
reduce the meta-package? :)

**Comment by jwt27** [comment]
The idea is that it contains everything, including all libraries (just those 2 for now).  But maybe I could split it into something like `djgpp-minimal` and `djgpp-all`.

**Comment by jwt27** [comment]
I updated openssl and zlib the other day, are you able to install it now on aarch64?

(of course, immediately after publishing I realized I should just set `Architecture: all` for cross libs...  will do that for the next version)

**Comment by stsp** [comment]
Yes, works for me, thanks!

**Comment by jwt27** [comment]
Alright, will close this then.
