### ISSUE TITLE
memalign() patch

### ISSUE THREAD

**Issue by rouseabout** [jwt27/build-gcc#5]
djlsr205 memalign is broken for large alignment values (e.g. 64).

Patch: <https://aur.archlinux.org/cgit/aur.git/tree/nmemalign.patch?h=djgpp-djcrx>

Discussion:  <http://www.delorie.com/archives/browse.cgi?p=djgpp/2017/12/29/16:26:58>

Test case:
```
#include <stdio.h>
#include <malloc.h>
int main()
{
        for (int alignment = 1; alignment <= 64; alignment *= 2) {
                void * ptr = memalign(alignment, 1*1024*1024);
                printf("%d: %p\n", alignment, ptr);
                if (ptr)
                        free(ptr);
        }
        return 0;
}
```

**Comment by jwt27** [comment]
Hey, thanks for the patch, and please excuse my slow response.
I merged it in but the test case still returns zero for values 16 and 64, is that supposed to happen?

**Comment by rouseabout** [comment]
you are right, the patch above dos not fix the problem.
i have switched to using another allocator: http://g.oswego.edu/dl/html/malloc.html

**Comment by jwt27** [comment]
I just realized, any patches to djgpp sources won't have any effect
since we're only downloading a precompiled libc.

The patch has been reverted for now. Maybe in a future update to the
build scripts we could patch and compile djgpp sources ourselves, even
the latest versions from cvs.

**Comment by jwt27** [comment]
Okay, big update. We're now building libc from source on branch `djgpp-cvs`, and I added the memalign patch again. As the branch name implies, we can now also build the latest djgpp from CVS, where I think this issue has been fixed already.

**Comment by jwt27** [comment]
Oh, looks like my force-pushing kept triggering a reference to this issue. I hope that didn't send out 7 emails. Anyway the test case works now for both 2.05 and cvs, so I'm closing this.

**Comment by rouseabout** [comment]
Thanks. Also works for me.

**Comment by stsp** [comment]
So is this project now the place for submitting
djgpp patches, or is there an alive upstream anywhere?
Can't find anything useful on delorie.com, but doing
`cvs up` shows a few commits, so maybe there is some
upstream after all.
Does anyone know?

**Comment by jwt27** [comment]
On 2019-08-02 12:04, Stas Sergeev wrote:
> So is this project now the place for submitting
> djgpp patches, or is there an alive upstream anywhere?
> Can't find anything useful on delorie.com, but doing
> |cvs up| shows a few commits, so maybe there is some
> upstream after all.
> Does anyone know?

Best place to send patches would be the mailing list, either 
djgpp@delorie.com or maybe djgpp-workers@delorie.com.
