### ISSUE TITLE
zic.exe: cannot execute binary file

### ISSUE THREAD

**Issue by stsp** [jwt27/build-gcc#7]
```
./build-djgpp.sh djgpp-cvs
[...]
../../hostbin/zic.exe  -y ./yearistype -d ../../zoneinfo -L /dev/null africa antarctica asia australasia europe northamerica southamerica pacificnew etcetera backward systemv factory solar87 solar88 solar89
../../hostbin/zic.exe: ../../hostbin/zic.exe: cannot execute binary file
make: *** [makefile:528: posix_only] Error 126
```

**Comment by jwt27** [comment]
This error is harmless and doesn't affect the rest of the build. You just don't get the zoneinfo files, but those are easily copied from elsewhere if you really need them. The tzdata included with djgpp is outdated anyway. However you still get libtz.a, for what it's worth. The official binaries for djgpp don't include this and I've never seen anyone complain that it's missing.
